# -*- coding: utf-8 -*-
"""Working_hour_calculation_on_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ju6cBI0fYgYFIwgkqx4SAbqZnsZ8UNNZ
"""

import streamlit as st
import calendar
import datetime

def count_saturdays_and_sundays(year):
    start_date = datetime.date(year, 1, 1)
    end_date = datetime.date(year, 12, 31)
    days_diff = (end_date - start_date).days + 1

    saturdays = 0
    sundays = 0

    for day in range(days_diff):
        current_date = start_date + datetime.timedelta(days=day)
        if current_date.weekday() == 5:  # Saturday
            saturdays += 1
        elif current_date.weekday() == 6:  # Sunday
            sundays += 1

    return saturdays, sundays

def number_of_days_in_year(year):
    if calendar.isleap(year):
        return 366
    else:
        return 365

def calculate_working_hours(year, hours_per_day, days_off, saturdays, sundays):
    days_in_year = number_of_days_in_year(year)
    working_days = days_in_year - days_off
    working_hours = working_days * hours_per_day
    working_hours_no_sat_sun = (working_days - saturdays - sundays) * hours_per_day
    return working_hours, working_hours_no_sat_sun

def decimal_to_hour_minute(decimal_value):
    hours = int(decimal_value)
    minutes = int((decimal_value - hours) * 60)
    return hours, minutes

# Streamlit app layout
    st.title('Working Hours Calculator')

    year = st.number_input('Year:', min_value=1900, max_value=2100, step=1)
    hours_per_day = st.number_input('Hours/day:', min_value=0.0, step=0.1)
    days_off = st.number_input('Days off:', min_value=0.0, step=0.1)

    if st.button('Calculate'):
        if not all([year, hours_per_day, days_off]):
             st.write('Please fill in all input fields.')
        else:
            saturdays, sundays = count_saturdays_and_sundays(year)
            working_hours, working_hours_no_sat_sun = calculate_working_hours(year, hours_per_day, days_off, saturdays, sundays)

            working_hours_h, working_hours_m = decimal_to_hour_minute(working_hours)
            working_hours_no_sat_sun_h, working_hours_no_sat_sun_m = decimal_to_hour_minute(working_hours_no_sat_sun)

            st.write(f'Total working hours: {working_hours_h} hours and {working_hours_m} minutes')
            st.write(f'Total working hours (excluding Saturdays and Sundays): {working_hours_no_sat_sun_h} hours and {working_hours_no_sat_sun_m} minutes')
            st.write(f'In {year}, there are {saturdays} Saturdays and {sundays} Sundays.')
